# app/Dockerfile

# --- Build Stage ---
FROM python:3.9-slim as builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# --- Final Stage ---
FROM python:3.9-slim
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages

# Copy only the final application code
COPY consumer.py .

# Run the main consumer application
CMD ["python", "consumer.py"]
